name: Website Deployment

on:
    push:
        branches: [ main ]
        paths:
            - turbo.json
            - apps/website/**
            - packages/ui/**
            - tooling/tailwind-config/**
            - .github/workflows/deploy-website.yaml
            - .do/app.yaml

permissions:
    contents: read
    packages: write
    actions: write
    id-token: write
    repository-projects: read

env:
    IMAGE_REGISTRY: ghcr.io
    IMAGE_TAG_SHA: ${{ github.sha }}
    PACKAGE_NAME: website

jobs:
    deploy-website:
        runs-on: ubuntu-latest
        environment: production
        concurrency:
            group: website-production
            cancel-in-progress: true
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Log in to the Github Container registry
                uses: docker/login-action@v3
                with:
                    registry: ${{ env.IMAGE_REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Set IMAGE_NAME with lower-cased repository
                run: |
                    echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}/${{ env.PACKAGE_NAME }}" >> "${GITHUB_ENV}"

            -   name: Docker meta
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images: |
                        ghcr.io/${{ env.IMAGE_NAME }}
                    tags: |
                        type=raw,value=latest,enable={{is_default_branch}}
                        type=ref,event=tag
                        type=raw,${{ env.IMAGE_TAG_SHA }}

            -   name: Build and push Docker image
                id: push
                uses: docker/build-push-action@v6.5.0
                with:
                    context: .
                    file: apps/website/Dockerfile
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    secrets: |
                        DOTENV_PRIVATE_KEY_PRODUCTION=${{ secrets.DOTENV_PRIVATE_KEY_WEBSITE_PRODUCTION }}

            -   name: Deploy the app
                uses: digitalocean/app_action/deploy@v2
                env:
                    IMAGE_DIGEST: ${{ steps.push.outputs.digest }}
                    IMAGE_REPOSITORY: ${{ github.event.repository.name }}/${{ env.PACKAGE_NAME }}
                    IMAGE_REGISTRY_CREDENTIALS: "${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}"
                    DOTENV_PRIVATE_KEY_WEBSITE_PRODUCTION: ${{ secrets.DOTENV_PRIVATE_KEY_WEBSITE_PRODUCTION }}
                with:
                    token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
